settings:
  title: 'Status Page'
  url: 'https://status.schwi-dola.cn' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-minaduki-cn # unique identifier
    name: www.minaduki.cn
    description: 'Something has to be written.' # default=empty
    url: 'https://www.minaduki.cn/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: sub-con # unique identifier
    name: sub.minaduki.cn
    description: 'Sub converter for clash and etc.' # default=empty
    url: 'https://sub.minaduki.cn/sub' # URL to fetch
    method: GET # default=GET
    expectStatus: 400 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: flase # allows the title to be a link, default=true
    
  - id: nju-itxia-cn # unique identifier
    name: nju.itxia.cn
    description: 'IT-xia Forever!' # default=empty
    url: 'https://nju.itxia.cn/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: nju-mirrors # unique identifier
    name: mirrors.nju.edu.cn
    description: 'NJU Open Source Mirror' # default=empty
    url: 'https://mirrors.nju.edu.cn/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: nju-overleaf # unique identifier
    name: tex.nju.edu.cn
    description: 'Sharelatex deployed by NJU' # default=empty
    url: 'https://tex.nju.edu.cn/login' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: zijingbt-mirror # unique identifier
    name: ZiJingBT Mirror
    description: 'A memorial for, at least, a part of my youth' # default=empty
    url: 'https://www.zijingbt.com/index.html' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: in-flame-team # unique identifier
    name: www.in-flame-team.com
    description: 'First blog built by me.' # default=empty
    url: 'https://www.in-flame-team.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
#  - id: minaduki-logistics # unique identifier
#    name: Minaduki Logistics
#    description: 'Minaduki Logistics remote access gateway' # default=empty
#    url: 'https://v4.logistics.minaduki.cn:5555/' # URL to fetch
#    method: GET # default=GET
#    expectStatus: 200 # operational status, default=200
#    followRedirect: true # should fetch follow redirects, default=false
#    linkable: false # allows the title to be a link, default=true      

#  - id: bill-backup # unique identifier
#    name: schwi-dola.com
#    description: 'Minaduki Logistics diskstation' # default=empty
#    url: 'https://schwi-dola.com:5001/' # URL to fetch
#    method: GET # default=GET
#    expectStatus: 200 # operational status, default=200
#    followRedirect: true # should fetch follow redirects, default=false
#    linkable: false # allows the title to be a link, default=true  
    
#  - id: seafile # unique identifier
#    name: Private Seafile
#    description: 'Private seafile server' # default=empty
#    url: 'https://seafile.minaduki.cn:8000/' # URL to fetch
#    method: GET # default=GET
#    expectStatus: 200 # operational status, default=200
#    followRedirect: false # should fetch follow redirects, default=false
#    linkable: false # allows the title to be a link, default=true  

  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200
